# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-11 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auto_20200210_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodityhome',
            name='cover',
            field=models.FileField(max_length=256, upload_to='', verbose_name='封面'),
        ),
    ]
