# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-11 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auto_20200211_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionItemDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=16, verbose_name='项')),
                ('value', models.CharField(max_length=32, verbose_name='值')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.ShowCommodity', verbose_name='拍品')),
            ],
            options={
                'verbose_name_plural': '拍品规格',
            },
        ),
    ]
