# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-11 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_auctionitemdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcommodity',
            name='cover',
            field=models.FileField(default=1, max_length=256, upload_to='', verbose_name='封面'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detailcommoditypic',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, '轮播'), (2, '详情')], default=1, verbose_name='图片类型'),
        ),
    ]
