# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-11 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_auto_20200211_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcommodity',
            name='uid',
            field=models.CharField(default=1, max_length=12, verbose_name='图录号'),
            preserve_default=False,
        ),
    ]
