# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-12 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_showcommodity_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcommodity',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, '未开拍'), (2, '预展中'), (3, '拍卖中'), (4, '成交'), (5, '流拍')], default=1, verbose_name='拍品状态'),
        ),
    ]
