# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-12 03:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_auto_20200212_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_task', models.CharField(max_length=64, verbose_name='Celery预展ID')),
                ('auction_task', models.CharField(max_length=64, verbose_name='Celery拍卖任务ID')),
                ('auction_end_task', models.CharField(max_length=64, verbose_name='Celery拍卖结束ID')),
                ('auction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auction.CommodityHome', verbose_name='专场')),
            ],
        ),
    ]
