# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-12 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_auctiontask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailcommoditypic',
            name='status',
        ),
        migrations.AddField(
            model_name='detailcommoditypic',
            name='carousel',
            field=models.BooleanField(default=False, verbose_name='是否在轮播中显示'),
        ),
    ]
