# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-12 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0010_remove_detailcommoditypic_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailcommoditypic',
            name='image_path',
            field=models.FileField(max_length=256, upload_to='', verbose_name='网络图片地址'),
        ),
    ]
