# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-13 05:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0013_auto_20200213_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionpayment',
            old_name='show_Auction',
            new_name='Auction_item',
        ),
    ]
