# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-13 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0014_auto_20200213_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcommodity',
            name='deal_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='成交价'),
        ),
        migrations.AlterField(
            model_name='showcommodity',
            name='min_price',
            field=models.IntegerField(verbose_name='起拍价格'),
        ),
    ]
