# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-13 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0015_auto_20200213_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcommodity',
            name='start_price',
            field=models.PositiveIntegerField(default=1, verbose_name='起拍价'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='showcommodity',
            name='max_price',
            field=models.IntegerField(verbose_name='参考最高价格'),
        ),
        migrations.AlterField(
            model_name='showcommodity',
            name='min_price',
            field=models.IntegerField(verbose_name='参考最低价格'),
        ),
    ]
