# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-13 06:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0016_auto_20200213_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositDeduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='余额')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.Order', verbose_name='订单')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='balance',
            field=models.PositiveIntegerField(default=1, verbose_name='金额'),
            preserve_default=False,
        ),
    ]
