# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-13 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0017_auto_20200213_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionpayment',
            old_name='Auction_item',
            new_name='auction_item',
        ),
    ]
