# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-13 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0018_auto_20200213_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name_plural': '保证记录'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='缴纳金额'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='balance',
            field=models.PositiveIntegerField(verbose_name='可用金额'),
        ),
    ]
