# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-13 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0020_auto_20200213_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '未支付'), (2, '待收货'), (3, '已完成'), (4, '逾期未支付')], default=1, verbose_name='状态'),
        ),
    ]
