# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-13 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0021_auto_20200213_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodityhome',
            name='total_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='全场拍卖总金额'),
        ),
    ]
