# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-14 05:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200213_2233'),
        ('auction', '0022_commodityhome_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '可领取'), (2, '已结束')], default=1, verbose_name='状态')),
                ('name', models.CharField(max_length=32, verbose_name='优惠卷名称')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='领取开始时间')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='领取结束时间')),
                ('price', models.IntegerField(verbose_name='抵扣金额')),
                ('cover', models.FileField(max_length=256, upload_to='', verbose_name='封面')),
                ('total_count', models.IntegerField(verbose_name='初始数量')),
                ('use_count', models.IntegerField(blank=True, null=True, verbose_name='领取数量')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.CommodityHome', verbose_name='专场')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '未使用'), (2, '已使用'), (3, '已过期')], default=1, verbose_name='状态')),
                ('dis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.Discounts', verbose_name='优惠卷')),
                ('ord', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.Order', verbose_name='订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserInfo', verbose_name='用户')),
            ],
        ),
    ]
