# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-14 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0023_discounts_discountsrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounts',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '未发放'), (2, '可领取'), (3, '已结束')], default=2, verbose_name='状态'),
        ),
    ]
