# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-15 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0024_auto_20200214_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='discounts',
            name='apply_start_task_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='celery开始ID'),
        ),
        migrations.AddField(
            model_name='discounts',
            name='apply_stop_task_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='celery结束ID'),
        ),
        migrations.AddField(
            model_name='discounts',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='use_count',
            field=models.IntegerField(default=0, verbose_name='领取数量'),
        ),
    ]
