# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-17 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0025_auto_20200215_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.DiscountsRecord', verbose_name='使用的优惠卷'),
        ),
        migrations.AddField(
            model_name='order',
            name='pay_type',
            field=models.PositiveSmallIntegerField(choices=[(1, '未支付'), (2, '待收货'), (3, '已完成'), (4, '逾期未支付')], default=2, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deposit_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='使用保证金金额'),
        ),
        migrations.AlterField(
            model_name='order',
            name='real_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='实际支付金额'),
        ),
    ]
