# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-17 04:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0026_auto_20200217_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
        migrations.AlterField(
            model_name='discountsrecord',
            name='dis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mydis', to='auction.Discounts', verbose_name='优惠卷'),
        ),
    ]
