# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-18 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0028_auto_20200217_1654'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiscountsRecord',
            new_name='Userdicount',
        ),
    ]
