# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-20 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0029_auto_20200218_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showcommodity',
            old_name='deal_price',
            new_name='end_price',
        ),
        migrations.RenameField(
            model_name='showcommodity',
            old_name='start_price',
            new_name='first_price',
        ),
    ]
