# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-20 03:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(blank=True, max_length=255, null=True, verbose_name='简介')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论数')),
                ('goods', models.IntegerField(default=0, verbose_name='点赞数')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('location', models.CharField(blank=True, max_length=64, null=True, verbose_name='地理位置')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='ArticleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('Coll_count', models.IntegerField(default=0, verbose_name='收藏数')),
            ],
            options={
                'verbose_name': '文章详细',
                'verbose_name_plural': '文章详细',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Article', verbose_name='文章收藏')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('depth', models.IntegerField(blank=True, default=0, verbose_name='评论深度')),
                ('favor_count', models.PositiveIntegerField(default=0, verbose_name='赞数')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Article', verbose_name='文章')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replys', to='api.Comment', verbose_name='回复的评论')),
                ('root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roots', to='api.Comment', verbose_name='根评论')),
            ],
            options={
                'verbose_name': '评论内容',
                'verbose_name_plural': '评论内容',
                'db_table': 'Comment',
            },
        ),
        migrations.CreateModel(
            name='goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Huati',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('count', models.IntegerField(default=0, verbose_name='人数')),
            ],
            options={
                'verbose_name': '话题',
                'verbose_name_plural': '话题',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(blank=True, max_length=256, null=True, verbose_name='文章图片路径')),
                ('atricle_image', models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.CASCADE, to='api.Article', verbose_name='图片外键')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickName', models.CharField(max_length=256, verbose_name='图片路径')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('avatarUrl', models.CharField(max_length=256, verbose_name='图片路径')),
                ('token', models.CharField(blank=True, max_length=64, null=True, verbose_name='用户TOKEN')),
                ('rpg', models.CharField(blank=True, choices=[(1, '普通用户'), (2, '管理员'), (3, '普通用户')], default=0, max_length=64, null=True, verbose_name='用户身份')),
                ('location', models.CharField(blank=True, max_length=64, null=True, verbose_name='地理位置')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='Vister_msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vister_count', models.IntegerField(default=0, verbose_name='浏览数')),
                ('article_detail', models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.CASCADE, to='api.ArticleDetail', verbose_name='文章详细')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserInfo', verbose_name='关联用户')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserInfo', verbose_name='评论者'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.UserInfo', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='article',
            name='detial',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ArticleDetail', verbose_name='文章表'),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.ForeignKey(max_length=31, on_delete=django.db.models.deletion.CASCADE, to='api.Huati', verbose_name='标题'),
        ),
    ]
