# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-23 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.CharField(default=1, max_length=255, verbose_name='简介'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.ForeignKey(blank=True, max_length=31, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Huati', verbose_name='标题'),
        ),
    ]
