# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-10 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200123_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='blance',
            field=models.CharField(default=0, max_length=32, verbose_name='余额'),
        ),
    ]
