# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-13 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200213_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='balance',
            field=models.IntegerField(default=0, max_length=32, verbose_name='余额'),
        ),
    ]
