# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-20 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200213_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='nickName',
            field=models.CharField(max_length=256, verbose_name='名称'),
        ),
    ]
