# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-20 05:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200220_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='nickname',
            new_name='nickName',
        ),
    ]
